// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rent.DataAccess.Context;

#nullable disable

namespace Rent.DataAccess.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20240702081616_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rent.DataAccess.Entities.VehicleClientHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VehicleClientHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26668b34-c23a-46a2-a2a3-1034671acacb"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000000"),
                            EndDate = new DateTime(2023, 9, 23, 20, 42, 0, 500, DateTimeKind.Utc).AddTicks(8584),
                            StartDate = new DateTime(2023, 8, 28, 11, 18, 12, 9, DateTimeKind.Utc).AddTicks(6795),
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a9387e8d-ba91-4f87-9fc8-cc8309515a12"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000000"),
                            EndDate = new DateTime(2024, 6, 25, 21, 36, 41, 479, DateTimeKind.Utc).AddTicks(4918),
                            StartDate = new DateTime(2023, 11, 23, 14, 4, 2, 653, DateTimeKind.Utc).AddTicks(4315),
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("55d70304-13c3-4d22-b6ac-42859a23f912"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000000"),
                            EndDate = new DateTime(2024, 1, 4, 16, 24, 29, 242, DateTimeKind.Utc).AddTicks(6142),
                            StartDate = new DateTime(2024, 3, 22, 7, 38, 0, 405, DateTimeKind.Utc).AddTicks(1235),
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c6c33095-990c-4593-a28d-d6f98fc068bb"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000000"),
                            EndDate = new DateTime(2023, 9, 7, 0, 32, 12, 359, DateTimeKind.Utc).AddTicks(1459),
                            StartDate = new DateTime(2024, 3, 21, 21, 16, 55, 891, DateTimeKind.Utc).AddTicks(113),
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d455df39-0d7f-4e16-846d-8e3b1e84909b"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000000"),
                            EndDate = new DateTime(2024, 4, 25, 11, 13, 45, 634, DateTimeKind.Utc).AddTicks(8015),
                            StartDate = new DateTime(2023, 10, 21, 8, 14, 17, 577, DateTimeKind.Utc).AddTicks(5577),
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
